# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6210b3654c85698891b7c8859e07d2b1e84410f0a7c691019acc62896880ae43745550067bc1ff16913ca9feb55c7665114a34056e0c136434a78be666cbcd7e

test:
  secret_key_base: 8606e41b32e45291ba97884dc3611262572aa45aaaabc07bdaf5b290ba67d9aad405b48c58d18417c1d9cebc33726b0bf80472f615f4e3a2e650870aa118300c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
